### ISSUE TITLE
Character walks through supercomputer

### ISSUE THREAD

**Issue by CubrYT** [waktool/RankQuests#16]
When I get a quest that has to do with the supercomputer it ends up behind the supercomputer because it's not one flat board. So what I was thinking is either you shorten the distance it walks to the right, or make a setting that says like max walk speed.

**Comment by ORIGINALBLACKPLAGUE** [comment]
I think probably a imagesearch would be best, as a trigger to stop the movement keypress when the supercomp is detected as opening, as well as a secondary image search to verify that the supercomputer buttons have spawned in the expected 6 wide configuration

**Comment by waktool** [comment]
Move away from the supercomputer:
`moveLeft(2000)`

Move back to the supercomputer:
`moveRight(2500)`
