### ISSUE TITLE
Item orbs get stuck on the price plate while hatching the best egg

### ISSUE THREAD

**Issue by CubrYT** [waktool/RankQuests#17]
![image](https://github.com/waktool/RankQuests/assets/167647156/5a1ee21f-b674-49e8-90c7-bc47580f6e7d)
This will cause lag when moved from hatching, and could break the macro

**Comment by waktool** [comment]
What should we do to resolve this issue? Is this for players without magnet enchants or magnet flags?

**Comment by CubrYT** [comment]
> What should we do to resolve this issue? Is this for players without magnet enchants or magnet flags?

I changed moveLeft(700 * SHINY_HOVERBOARD_MODIFIER) to moveLeft(700 * SHINY_HOVERBOARD_MODIFIER)

and I have Super Magnet but It would also do this for the normal magnet enchant. I did not have magnet flags on either.

**Comment by waktool** [comment]
This issue has been resolved with the latest PS99 updates.
